In [27]:
from typing import List, Optional, Tuple, Union
import numpy as np


def simple_great_circle_path(
    *, T: float = 15.0, dt: float = 0.1, d: int = 3, speed: float = 1.0
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Single-particle great-circle trajectory on the unit d-sphere.

    Returns
    -------
    interject_ts : ndarray, shape (num_steps, d)
        The position at every time step.
    t_grid       : ndarray, shape (num_steps,)
        Matching time stamps.
    """
    assert d >= 2, "d must be at least 2 for a great circle"
    num_steps = int(T / dt) + 1
    t_grid = np.linspace(0.0, T, num_steps)

    # pre-allocate for speed; (num_steps, d)
    z = np.zeros((num_steps, d))
    z[:, 0] = np.cos(speed * t_grid)   # x1
    z[:, 1] = np.sin(speed * t_grid)   # x2
    # remaining coordinates stay zero

    return z, t_grid

In [32]:
i_ts, t_grid = simple_great_circle_path()
i_ts

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.99500417,  0.09983342,  0.        ],
       [ 0.98006658,  0.19866933,  0.        ],
       [ 0.95533649,  0.29552021,  0.        ],
       [ 0.92106099,  0.38941834,  0.        ],
       [ 0.87758256,  0.47942554,  0.        ],
       [ 0.82533561,  0.56464247,  0.        ],
       [ 0.76484219,  0.64421769,  0.        ],
       [ 0.69670671,  0.71735609,  0.        ],
       [ 0.62160997,  0.78332691,  0.        ],
       [ 0.54030231,  0.84147098,  0.        ],
       [ 0.45359612,  0.89120736,  0.        ],
       [ 0.36235775,  0.93203909,  0.        ],
       [ 0.26749883,  0.96355819,  0.        ],
       [ 0.16996714,  0.98544973,  0.        ],
       [ 0.0707372 ,  0.99749499,  0.        ],
       [-0.02919952,  0.9995736 ,  0.        ],
       [-0.12884449,  0.99166481,  0.        ],
       [-0.22720209,  0.97384763,  0.        ],
       [-0.32328957,  0.94630009,  0.        ],
       [-0.41614684,  0.90929743,  0.   

In [39]:
import particle_simulators as ps
from importlib import reload
reload(ps)

<module 'particle_simulators' from '/Users/masomatics/Library/CloudStorage/GoogleDrive-koyama.masanori@gmail.com/マイドライブ/mptf_exps/particle_simulators.py'>

In [40]:
z_list, t_grid = ps.InterJectorSimulator(interject_ts=i_ts) 

AssertionError: expected interject_ts with shape (T, K, d)

/var/folders/xf/kry31x253qx54lk16j5mm6j00000gn/T/ipykernel_36524/3131988748.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(i_ts)


array([[array([1., 0., 0.]), array([0.99500417, 0.09983342, 0.        ]),
        array([0.98006658, 0.19866933, 0.        ]),
        array([0.95533649, 0.29552021, 0.        ]),
        array([0.92106099, 0.38941834, 0.        ]),
        array([0.87758256, 0.47942554, 0.        ]),
        array([0.82533561, 0.56464247, 0.        ]),
        array([0.76484219, 0.64421769, 0.        ]),
        array([0.69670671, 0.71735609, 0.        ]),
        array([0.62160997, 0.78332691, 0.        ]),
        array([0.54030231, 0.84147098, 0.        ]),
        array([0.45359612, 0.89120736, 0.        ]),
        array([0.36235775, 0.93203909, 0.        ]),
        array([0.26749883, 0.96355819, 0.        ]),
        array([0.16996714, 0.98544973, 0.        ]),
        array([0.0707372 , 0.99749499, 0.        ]),
        array([-0.02919952,  0.9995736 ,  0.        ]),
        array([-0.12884449,  0.99166481,  0.        ]),
        array([-0.22720209,  0.97384763,  0.        ]),
        array([-

In [44]:
np.full(3, 1.0)

array([1., 1., 1.])