In [1]:
ls

README.md       simulators.py   Untitled.ipynb  visualize.py


In [4]:
import sys
sys.path.append('./')
import visualize as vis
import simulators as sim 
from importlib import reload 
import numpy as np
reload(vis)

<module 'visualize' from '/Users/masomatics/Library/CloudStorage/GoogleDrive-koyama.masanori@gmail.com/マイドライブ/mptf_exps/visualize.py'>

In [41]:
myseed = 14
z, t_grid = sim.simulate_particles(seed=myseed)
print(np.mean(z[:, -1, :], axis=0))

Calling simulate_particles with:
    n=64, T=15, dt=0.1, d=3, beta=1, half_sph=False, seed=14
[-0.45014624 -0.8926474   0.02311111]


In [42]:
pre_anchor = np.mean(z[:, -1, :], axis=0)
anchor = pre_anchor / np.linalg.norm(pre_anchor) 
print(pre_anchor)
print(anchor)

[-0.45014624 -0.8926474   0.02311111]
[-0.45014958 -0.89265403  0.02311129]


In [45]:
reload(sim)

z2, t_grid2 = sim.simulate_particles_with_anchor(seed=myseed, anchor=anchor, T=200, anchor_weight=1.0 )

print(z2[-10:, -1, :])
print(z2.shape)

Calling simulate_particles with:
    n=64, T=200, dt=0.1, d=3, beta=1, half_sph=False, seed=14
Anchor point: [-0.45014958 -0.89265403  0.02311129], weight: 1.0
[[-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45014958 -0.89265403  0.02311129]]
(65, 2001, 3)


In [25]:
reload(vis)
vis.render(z2, 3, t_grid2,rootdrivepath='./figs',
    color='#3658bf',
    movie=True,
    fps=10,
    m=64,
    color_rest='#d94f4f',
    interpolate=True)

render: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:16<00:00,  9.04it/s]


GIF saved → ./figs/sphere/beta=1/09-43-53_movie.gif


In [58]:
A = np.eye(3)
anchor_weight= 1.0
z4Attn = z[:, 0].copy()  # Copy current positions for attention calculation
z4Attn[-1] = z4Attn[-1] * anchor_weight # Scale anchor point for attention   
Az           = (A @ z4Attn.T).T

In [59]:
Az_copy = (A @ z[:, 0].T).T

In [60]:
(Az == Az_copy).all()

True

In [62]:

from typing import List, Optional, Tuple, Union


def simple_great_circle_path(
    *, T: float = 15.0, dt: float = 0.1, d: int = 3, speed: float = 1.0
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Single-particle great-circle trajectory on the unit d-sphere.

    Returns
    -------
    interject_ts : ndarray, shape (num_steps, d)
        The position at every time step.
    t_grid       : ndarray, shape (num_steps,)
        Matching time stamps.
    """
    assert d >= 2, "d must be at least 2 for a great circle"
    num_steps = int(T / dt) + 1
    t_grid = np.linspace(0.0, T, num_steps)

    # pre-allocate for speed; (num_steps, d)
    z = np.zeros((num_steps, d))
    z[:, 0] = np.cos(speed * t_grid)   # x1
    z[:, 1] = np.sin(speed * t_grid)   # x2
    # remaining coordinates stay zero

    return z, t_grid

In [64]:
simple_great_circle_path()

([array([[1., 0., 0.]]),
  array([[0.99500417, 0.09983342, 0.        ]]),
  array([[0.98006658, 0.19866933, 0.        ]]),
  array([[0.95533649, 0.29552021, 0.        ]]),
  array([[0.92106099, 0.38941834, 0.        ]]),
  array([[0.87758256, 0.47942554, 0.        ]]),
  array([[0.82533561, 0.56464247, 0.        ]]),
  array([[0.76484219, 0.64421769, 0.        ]]),
  array([[0.69670671, 0.71735609, 0.        ]]),
  array([[0.62160997, 0.78332691, 0.        ]]),
  array([[0.54030231, 0.84147098, 0.        ]]),
  array([[0.45359612, 0.89120736, 0.        ]]),
  array([[0.36235775, 0.93203909, 0.        ]]),
  array([[0.26749883, 0.96355819, 0.        ]]),
  array([[0.16996714, 0.98544973, 0.        ]]),
  array([[0.0707372 , 0.99749499, 0.        ]]),
  array([[-0.02919952,  0.9995736 ,  0.        ]]),
  array([[-0.12884449,  0.99166481,  0.        ]]),
  array([[-0.22720209,  0.97384763,  0.        ]]),
  array([[-0.32328957,  0.94630009,  0.        ]]),
  array([[-0.41614684,  0.909297