In [1]:
ls

README.md       simulators.py   Untitled.ipynb  visualize.py


In [4]:
import sys
sys.path.append('./')
import visualize as vis
import simulators as sim 
from importlib import reload 
import numpy as np
reload(vis)

<module 'visualize' from '/Users/masomatics/Library/CloudStorage/GoogleDrive-koyama.masanori@gmail.com/マイドライブ/mptf_exps/visualize.py'>

In [41]:
myseed = 14
z, t_grid = sim.simulate_particles(seed=myseed)
print(np.mean(z[:, -1, :], axis=0))

Calling simulate_particles with:
    n=64, T=15, dt=0.1, d=3, beta=1, half_sph=False, seed=14
[-0.45014624 -0.8926474   0.02311111]


In [42]:
pre_anchor = np.mean(z[:, -1, :], axis=0)
anchor = pre_anchor / np.linalg.norm(pre_anchor) 
print(pre_anchor)
print(anchor)

[-0.45014624 -0.8926474   0.02311111]
[-0.45014958 -0.89265403  0.02311129]


In [45]:
reload(sim)

z2, t_grid2 = sim.simulate_particles_with_anchor(seed=myseed, anchor=anchor, T=200, anchor_weight=1.0 )

print(z2[-10:, -1, :])
print(z2.shape)

Calling simulate_particles with:
    n=64, T=200, dt=0.1, d=3, beta=1, half_sph=False, seed=14
Anchor point: [-0.45014958 -0.89265403  0.02311129], weight: 1.0
[[-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45350202 -0.89103621  0.01975848]
 [-0.45014958 -0.89265403  0.02311129]]
(65, 2001, 3)


In [25]:
reload(vis)
vis.render(z2, 3, t_grid2,rootdrivepath='./figs',
    color='#3658bf',
    movie=True,
    fps=10,
    m=64,
    color_rest='#d94f4f',
    interpolate=True)

render: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:16<00:00,  9.04it/s]


GIF saved → ./figs/sphere/beta=1/09-43-53_movie.gif
