In [36]:
from typing import List, Optional, Tuple, Union
import numpy as np
import particle_simulators as ps
from importlib import reload
import visualize as vis
reload(vis)
reload(ps)

<module 'particle_simulators' from '/Users/masomatics/Library/CloudStorage/GoogleDrive-koyama.masanori@gmail.com/マイドライブ/mptf_exps/particle_simulators.py'>

In [22]:
anchor1= np.array([1., 0, 0]) 
anchor2= np.array([0, 1., 0])

anchors = np.vstack((anchor1, anchor2))
print(anchors)

[[1. 0. 0.]
 [0. 1. 0.]]


In [49]:
myseed= 10
weight = 2
T = 15
z_list, t_grid = ps.simulate_particles_with_anchor(
        seed=myseed,
        anchor=anchors,T=T,
        anchor_weight=weight
    )
print(z_list[-1].shape)

Calling simulate_particles with (multi-anchor, population mode):
            free_n0=64, M=2, T=15, dt=0.1, d=3, beta=1.0,
            half_sph=False, seed=10
Anchors (rows):
 [[1. 0. 0.]
 [0. 1. 0.]]
 weights: [2. 2.]
(66, 3)


In [50]:
vis.render(z_list, 3,  t_grid, m=64, rootdrivepath='./figs', movie=True, fps=10,  title=f"dual_anchors_weight{weight}", interpolate=True) 

render: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:09<00:00, 15.95it/s]


GIF saved → ./figs/sphere/beta=1/17-45-07_dual_anchors_weight2_movie.gif


In [53]:
myseed= 10
weight = 2
T = 15

anchorweights=[1,2,4,8,16]
for weight in anchorweights:
    z_list, t_grid = ps.simulate_particles_with_anchor(
            seed=myseed,
            anchor=anchors,T=T,
            anchor_weight=weight
        )
    print(z_list[-1].shape)
    vis.render(z_list, 3,  t_grid, m=64, rootdrivepath='./figs', movie=True, fps=10,  title=f"dual_anchors_weight{weight}", interpolate=True) 

Calling simulate_particles with (multi-anchor, population mode):
            free_n0=64, M=2, T=15, dt=0.1, d=3, beta=1.0,
            half_sph=False, seed=10
Anchors (rows):
 [[1. 0. 0.]
 [0. 1. 0.]]
 weights: [1. 1.]
(66, 3)


render: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:07<00:00, 19.52it/s]


GIF saved → ./figs/sphere/beta=1/17-47-11_dual_anchors_weight1_movie.gif
Calling simulate_particles with (multi-anchor, population mode):
            free_n0=64, M=2, T=15, dt=0.1, d=3, beta=1.0,
            half_sph=False, seed=10
Anchors (rows):
 [[1. 0. 0.]
 [0. 1. 0.]]
 weights: [2. 2.]
(66, 3)


render: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:07<00:00, 19.08it/s]


GIF saved → ./figs/sphere/beta=1/17-47-28_dual_anchors_weight2_movie.gif
Calling simulate_particles with (multi-anchor, population mode):
            free_n0=64, M=2, T=15, dt=0.1, d=3, beta=1.0,
            half_sph=False, seed=10
Anchors (rows):
 [[1. 0. 0.]
 [0. 1. 0.]]
 weights: [4. 4.]
(66, 3)


render: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:07<00:00, 19.51it/s]


GIF saved → ./figs/sphere/beta=1/17-47-45_dual_anchors_weight4_movie.gif
Calling simulate_particles with (multi-anchor, population mode):
            free_n0=64, M=2, T=15, dt=0.1, d=3, beta=1.0,
            half_sph=False, seed=10
Anchors (rows):
 [[1. 0. 0.]
 [0. 1. 0.]]
 weights: [8. 8.]
(66, 3)


render: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:08<00:00, 18.28it/s]


GIF saved → ./figs/sphere/beta=1/17-48-02_dual_anchors_weight8_movie.gif
Calling simulate_particles with (multi-anchor, population mode):
            free_n0=64, M=2, T=15, dt=0.1, d=3, beta=1.0,
            half_sph=False, seed=10
Anchors (rows):
 [[1. 0. 0.]
 [0. 1. 0.]]
 weights: [16. 16.]
(66, 3)


render: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:08<00:00, 18.28it/s]


GIF saved → ./figs/sphere/beta=1/17-48-19_dual_anchors_weight16_movie.gif


In [54]:
for k in range(len(z_list)):
    print(len(z_list[k]))

66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
66
